// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AbilityStats: typeof import('./src/components/StatsComponent/AbilityStats.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    EvolutionComponent: typeof import('./src/components/StatsComponent/EvolutionComponent.vue')['default']
    GeneralStats: typeof import('./src/components/StatsComponent/GeneralStats.vue')['default']
    PokedexFooter: typeof import('./src/components/PokedexFooter.vue')['default']
    PokedexHeader: typeof import('./src/components/PokedexHeader.vue')['default']
    PokeMainContent: typeof import('./src/components/PokeMainContent.vue')['default']
    StatsValueDisplay: typeof import('./src/components/StatsComponent/StatsValueDisplay.vue')['default']
  }
}

export { }
